### ISSUE TITLE
Error with Dual Shock 4

### ISSUE THREAD

**Issue by TeddyDD** [go-gl/glfw#333] opened 2021-08-30 05:21 UTC
```
[...]
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 030000004c050000cc09000011810000 (PS4 Controller)
GLFW: Please report this bug in the Go package immediately.
panic: InvalidValue: Invalid button in gamepad mapping 030000004c050000cc09000011810000 (PS4 Controller)

goroutine 1 [running]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0xc00011a9e0})
	/home/teddy/src/darktile/vendor/github.com/go-gl/glfw/v3.3/glfw/error.go:174 +0x186
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	/home/teddy/src/darktile/vendor/github.com/go-gl/glfw/v3.3/glfw/error.go:185
github.com/go-gl/glfw/v3.3/glfw.WindowHint(0xc00018e000, 0xb49400)
	/home/teddy/src/darktile/vendor/github.com/go-gl/glfw/v3.3/glfw/window.go:275 +0x3f
github.com/hajimehoshi/ebiten/v2/internal/glfw.WindowHint(...)
	/home/teddy/src/darktile/vendor/github.com/hajimehoshi/ebiten/v2/internal/glfw/glfw_notwindows.go:372
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.initialize()
	/home/teddy/src/darktile/vendor/github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw/ui.go:179 +0x85
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.init.1()
	/home/teddy/src/darktile/vendor/github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw/ui.go:159 +0x19
```

Related to #274

**Comment by hajimehoshi** [comment] 2021-09-06 16:06
Does this still occur with the latest Ebiten?

**Comment by TeddyDD** [comment] 2021-09-08 07:32
Yes (v2.2.0-alpha.13)

**Comment by hajimehoshi** [comment] 2021-09-08 07:34
Sure, thanks. Unfortunately we cannot handle this on GLFW/Ebiten side. I think this will be fixed at GLFW 3.3.5 (https://github.com/glfw/glfw/issues/1763)

**Comment by hajimehoshi** [comment] 2021-09-08 07:36
> Invalid button in gamepad mapping

On second thought, this seems an error after a mapping was found but a button assignment was wrong. I'll take a look.

Which OS are you using?

**Comment by TeddyDD** [comment] 2021-09-08 08:28
Linux 5.13, x86_64

**Comment by hajimehoshi** [comment] 2021-09-08 13:42
I tested my PS4 controller `030000004c050000c405000011810000` on Mint Linux but could not reproduce this.

```
             ...-:::::-...                 parallels@parallels-Parallels-Virtual-Platform 
          .-MMMMMMMMMMMMMMM-.              ---------------------------------------------- 
      .-MMMM`..-:::::::-..`MMMM-.          OS: Linux Mint 20 x86_64 
    .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.        Host: Parallels Virtual Platform None 
   -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-       Kernel: 5.4.0-74-generic 
 `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`    Uptime: 5 mins 
 :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:    Packages: 2442 (dpkg), 3 (flatpak) 
.MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.   Shell: bash 5.0.17 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   Resolution: 3360x2100 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:   DE: Cinnamon 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   WM: Mutter (Muffin) 
.MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.   WM Theme: Mint-Y-Dark (Mint-Y) 
 :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:    Theme: Mint-Y [GTK2/3] 
  :MMM:MMM:`                `:MMM:MMM:     Icons: Mint-Y [GTK2/3] 
   .MMM.MMMM:--------------:MMMM.MMM.      Terminal: gnome-terminal 
     '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'       CPU: Intel i7-1068NG7 (2) @ 2.304GHz 
       '.-MMMM``--:::::--``MMMM-.'         GPU: 01:00.0 Parallels, Inc. Accelerated Virtual Video Adapter 
            '-MMMMMMMMMMMMM-'              Memory: 850MiB / 1981MiB 
               ``-:::::-``
                                                                   
                                                                   
```

Could you show me a minimized code to reproduce this issue? Thanks!

**Comment by hajimehoshi** [comment] 2021-09-08 13:51
And probably (not 100% sure) this is an issue for Ebiten. I'll transfer this issue to github.com/hajimehoshi/ebiten

**Comment by hajimehoshi** [comment] 2021-09-08 13:54
Let's continue to discuss at https://github.com/hajimehoshi/ebiten/issues/1802

**Closed as completed by hajimehoshi** 2021-09-08 13:54 UTC

**Comment by hajimehoshi** [comment] 2021-09-11 13:52
Note: Ebiten fixed this by NOT using GLFW's gamepad mappings. So, this issue still exists on GLFW side.
