### ISSUE TITLE
Consider changing GetCocoaWindow et al. signatures to return unsafe.Pointer rather than uintptr.

### ISSUE THREAD

**Issue by dmitshur** [go-gl/glfw#230] opened 2018-10-22 07:23 UTC
The motivation is to be able to get rid of the `possible misuse of unsafe.Pointer` messages from `go vet`, due to user being forced to convert `uintptr` back to `unsafe.Pointer`.

See discussion around https://github.com/go-gl/gl/issues/113#issuecomment-431740463. /cc @slimsag

If we're in agreement this is a good idea and the right way forward, the question will be whether to do this for 3.2 (a breaking API change), or 3.3 only (still in development).

**Comment by tapir** [comment] 2018-10-23 11:54
I'm OK with the change for 3.3 branch.
As it's not a bug I would not like to break API for 3.2

**Comment by pwaller** [comment] 2019-11-24 19:54
Hopefully this is addressed in #256, which introduces glfw 3.3 support. If not please report back and we can reopen.

@dmitshur I can confirm that `go vet` doesn't emit any warnings for me on Linux. Does that prove that this issue is resolved? It would be helpful to have a minimal reproducer to check.

**Closed as completed by pwaller** 2019-11-24 19:54 UTC
Labels: glfw-3.3
