### ISSUE TITLE
NotInitialized: The GLFW library is not initialized

### ISSUE THREAD

**Issue by marti1125** [go-gl/glfw#266] opened 2020-02-07 23:50 UTC
Hi just create a example follow the README.

sry. I don't know about error I am new using go + opengl

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

go version go1.13.4 linux/amd64

```
package main

import (
	"github.com/go-gl/glfw/v3.3/glfw"
	"runtime"
)

func init() {
	// This is needed to arrange that main() runs on main thread.
	// See documentation for functions that are only allowed to be called from the main thread.
	runtime.LockOSThread()
}

func main() {
	err := glfw.Init()
	if err != nil {
		panic(err)
	}
	defer glfw.Terminate()

	window, err := glfw.CreateWindow(640, 480, "Testing", nil, nil)
	if err != nil {
		panic(err)
	}

	window.MakeContextCurrent()

	for !window.ShouldClose() {
		// Do OpenGL stuff.
		window.SwapBuffers()
		glfw.PollEvents()
	}
}
```

```
module github.com/marti1125/guess

go 1.13

require (
	github.com/go-gl/glfw/v3.3/glfw v0.0.0-20191125211704-12ad95a8df72
)
```

```
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0xc0000bbe58, 0x2, 0x2, 0x0, 0x0)
        /home/willy.aguirre/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20191125211704-12ad95a8df72/error.go:174 +0x216
github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0x280, 0x1e0, 0x4fad45, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/willy.aguirre/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20191125211704-12ad95a8df72/window.go:350 +0x1c1
main.main()
        /home/willy.aguirre/go/src/github.com/marti1125/guess/main.go:21 +0xa9
exit status 2
```

**Comment by marti1125** [comment] 2020-02-07 23:52
libgl1-mesa-dev  (19.2.8-0ubuntu0~18.04.1)
xorg-dev  (1:7.7+19ubuntu7.1).

**Comment by pwaller** [comment] 2020-02-09 16:26
Description:	Ubuntu 18.04.4 LTS
go version go1.13.3 linux/amd64
libgl1-mesa-dev: 19.2.8-0ubuntu0~18.04.2
xorg-dev: 1:7.7+19ubuntu7.1

I am unable to reproduce here, with an Nvidia 1080 GTX. I took your go.mod and your source verbatim. When I run it, I get a black window, which I guess is as expected.

Please can you, if possible:
* provide hardware information?
* attach the output of `glxinfo` (from the `mesa-utils` package)
* can you run, e.g. `glxgears` (also from `mesa-utils`)?
* test an equivalent C program.

I suspect this is an issue in glfw itself rather than the go bindings. It's unlikely we're able to help here, as resources are limited, and I wasn't able to reproduce yet.

**Comment by marti1125** [comment] 2020-02-09 19:44
I just installed mesa-utils, and works!

```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)  (0x5917)
    Version: 19.2.8
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2

```

**Comment by pwaller** [comment] 2020-02-09 20:43
Hi @marti1125 thanks for reporting back and closing the issue.

Are you saying that installing mesa-utils fixed the issue? That seems unexpected to me! :) -- at least it's not listed as one of our dependencies, and I wouldn't expect it to be necessary. Uninstalling the package here with `apt remove mesa-utils` still does not reproduce the issue for me, as expected.

* Please could you take a look at your `/var/log/apt/history.log` (or `/history.log.N`) to identify the time you installed mesa-util, and identify what else got installed at that time? If you could share the log fragment that could be a great help to prevent others from hitting this.

* Please can you `apt remove mesa-utils` and confirm that your application continues to work, as it does for me?

Reopening to see if we have a chance to nail this.

Thanks!

**Comment by marti1125** [comment] 2020-02-09 21:07
Start-Date: 2020-02-07  20:14:05
Commandline: apt install libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev libasound2-dev
Requested-By: willy.aguirre (16777218)
Install: libglu1-mesa-dev:amd64 (9.0.0-2.1build1), libasound2-dev:amd64 (1.1.3-5ubuntu0.2)
End-Date: 2020-02-07  20:14:06

Start-Date: 2020-02-09  15:57:33
Commandline: apt install mesa-utils
Requested-By: willy.aguirre (16777218)
Install: mesa-utils:amd64 (8.4.0-1)
End-Date: 2020-02-09  15:57:35

Start-Date: 2020-02-09  17:46:42
Commandline: apt remove mesa-utils
Requested-By: willy.aguirre (16777218)
Remove: mesa-utils:amd64 (8.4.0-1)
End-Date: 2020-02-09  17:46:44


Yes after delete mesa-util it's still works. I think I had to restart it

**Comment by pwaller** [comment] 2020-02-11 20:54
OK, then I guess we have to leave this as a mystery. If you're able to discover what breaks it, please report back and we'll reopen!

Thanks for responding.

**Closed as completed by pwaller** 2020-02-11 20:54 UTC

**Comment by gitouni** [comment] 2022-03-27 03:36
I met this problem when import open3d.webvisualizer in remote server through ssh:
`from open3d.web_visualizer import draw`
I tackled this problem after the line above was commented.

**Comment by snoweuph** [comment] 2024-09-14 20:04
I get the Exact same problem under KDE Plasma Wayland under Fedora,

No Window that opens, jsut this crash
```go
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0x0?})
        /home/snoweuph/.local/share/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-202405
06104042-037f3cc74f2a/error.go:177 +0x170
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        /home/snoweuph/.local/share/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-202405
06104042-037f3cc74f2a/error.go:188
github.com/go-gl/glfw/v3.3/glfw.(*Window).ShouldClose(0x4cfac8?)
        /home/snoweuph/.local/share/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-202405
06104042-037f3cc74f2a/window.go:370 +0x25
dev.euph.git/snoweuph/game-engine/pkg/engine/adapters/window/glfw.GLFWWindow.ShouldClose(...
)
        /home/snoweuph/Workspace/GameEngine/pkg/engine/adapters/window/glfw/window.go:37
main.main()
        /home/snoweuph/Workspace/GameEngine/cmd/game/main.go:20 +0x5b
error: Recipe `run` failed on line 11 with exit code 2
```

**Comment by snoweuph** [comment] 2024-09-14 20:09
Installing `mesa-demos` the equivalent of `mesa-utils` on fedora, did not fix it for me

**Comment by snoweuph** [comment] 2024-09-14 20:10
im running wayland btw, and yes I intsalled the stuff from the readme

**Comment by snoweuph** [comment] 2024-09-15 09:02
Ahh, I see, m problem seems to be thread related, damn.

Also looks like this library does not use GLFW Wayland and only Xorg

**Comment by GwynethLlewelyn** [comment] 2025-01-03 00:49
I get this error on the Raspberry Pi (Zero 2 W) as well — although one possible reason for that is the (incomplete?) support provided by the Wayland-ish configuration on the Pi. On the other hand, I'm _not_ using a locally-connected display; instead, I'm using XQuartz 2.8.5 (xorg-server 21.1.6) on macOS, and funnelling the connection through `ssh -X ...`. 

For the sake of completeness:

```sh
$ glxinfo
name of display: localhost:10.0
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Serial number of failed request:  27
  Current serial number in output stream:  28

$ glxgears
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Error: glXCreateContext failed
```

Somewhere else I read that sometimes setting `export LIBGL_ALWAYS_INDIRECT=1` helps. Well, in my case, it certainly skips a few errors:

```sh
$ glxinfo
name of display: localhost:10.0
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Serial number of failed request:  17
  Current serial number in output stream:  18

$ glxgears
Error: glXCreateContext failed
```
Interestingly, with `LIBGL_ALWAYS_INDIRECT` set to 1, my Go application (written on top of [Fyne](https://github.com/fyne-io/fyne)) complains of something else:

```sh
$ ./myapp
2025/01/02 21:13:12 Fyne error:  window creation error
2025/01/02 21:13:12   Cause: APIUnavailable: GLX: OpenGL ES requested but GLX_EXT_create_context_es2_profile is unavailable
2025/01/02 21:13:12   At: /home/gwyneth/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/internal/driver/glfw/driver_notwindows.go:8
```

Note that the usual X applets (xeyes, xclock, etc.) all work flawlessly and very quickly, without the slightest shadow of an error.

So, my best guess is that, in my case, it's just a coincidence that, under some circumstances, I get the 'GLFW library is not initialised' error. A lot of other things might be wrong:

1. Xquartz, providing the Xorg server on macOS, might be too outdated, or refusing to load certain libraries that enable GLFW.
  - Alternatively, there might be some libraries completely missing on macOS to support GLFW and satisfy its dependencies.
2. The humble Raspberry Pi Zero 2 W is not up to the task, for several reasons:
  - Its graphics card might be simply too underpowered, and therefore existing functionality is reduced to the essential minimum; this might even affect applications running on _external_ (i.e., non-local) X servers.
  - The X11-over-Wayland implementation might be just a subset that doesn't implement _everything_, just the bare bones that enable xclock, xeyes, etc. to work, but anything else will simply fail with the lack of full support for _all_ functionality.
  - Or: everything might simply require a bit more footprint (memory, CPU, graphics, or appropriate libraries) than what a Raspberry PI can provide...
3. The X communication protocol might be incompletely/incorrectly implemented, either on the Pi or on Xquartz, so the Pi cannot 'tell' Xquartz what it needs, because it lacks the ability to do so (at the library level). In other words:
  - The Pi might be unable to make requests from a _remote_ X server for which it lacks a _local_ equivalent (i.e., it doesn't ask for more than is actually possible on its locally-installed library); _or_
  - macOS is also similarly handicapped, with Xquartz refusing to provide anything beyond the bare-bones functionality that Apple had put in it, 15 years ago or more, and quickly abandoned its own efforts to 'reinvent the wheel' — they already had something that worked on _their_ hardware, so, why bother with anything else?
  - Over the years, the volunteers that have been supporting Xquartz have abandoned the project and have moved on to other more interesting ones.

Taking all the above in account, it's more than likely that my own issues are _directly_ relevant to this specific error; it was just a coincidence...

But in the faint hope that there might be something that might trigger that 'Eureka!' moment, I decided to append my own report here as well.
